# Generated by Django 5.2.5 on 2025-10-09 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boarding_points", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("driver", "Driver"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "class_shift",
                    models.CharField(
                        choices=[
                            ("M", "Morning"),
                            ("A", "Afternoon"),
                            ("E", "Evening"),
                            ("M-A", "Morning & Afternoon"),
                            ("A-E", "Afternoon & Evening"),
                        ]
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        choices=[
                            ("UESPI", "Universidade Estadual do Piauí"),
                            ("CHRISFAPI", "Christus Faculdade do Piauí"),
                            ("IFPI", "Instituto Federal do Piauí"),
                            ("ETC", "Outro"),
                        ]
                    ),
                ),
                (
                    "boarding_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="boarding_points.boardingpoint",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
