# Generated by Django 5.2.5 on 2025-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="monthly_payment_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="payment_day",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
