# Generated by Django 5.2.5 on 2025-11-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_monthly_payment_cents_student_payment_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="payment_day",
        ),
        migrations.AddField(
            model_name="student",
            name="last_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
