# Generated by Django 5.2.5 on 2025-11-05 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=11)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("driver", "Driver"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("M", "Morning"),
                            ("A", "Afternoon"),
                            ("E", "Evening"),
                            ("M-A", "Morning & Afternoon"),
                            ("A-E", "Afternoon & Evening"),
                        ]
                    ),
                ),
                ("dailyPaymentCents", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
