# Generated by Django 5.2.5 on 2025-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("employee", "Employee"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
