# Generated by Django 5.2.5 on 2025-10-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="dailyPaymentCents",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="driver",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("driver", "Driver"),
                    ("admin", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
