# Generated by Django 5.2.5 on 2025-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="current_university",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
