# Generated by Django 5.2.5 on 2025-09-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ex: Praça Central, Posto Shell", max_length=255
                    ),
                ),
                (
                    "address_reference",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Em frente à farmácia",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "route_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem em que o motorista passa no ponto (0, 1, 2...)",
                    ),
                ),
            ],
            options={
                "ordering": ["route_order"],
            },
        ),
    ]
