# Generated by Django

from django.db import migrations

def forwards_func(apps, schema_editor):
    """
    Copia os dados da tabela antiga (common_boardingpoint)
    para a nova tabela (boarding_points_boardingpoint).
    """
    # Usamos apps.get_model para pegar as versões históricas dos modelos
    # para garantir que a migração seja sempre reproduzível.
    OldBoardingPoint = apps.get_model("common", "BoardingPoint")
    NewBoardingPoint = apps.get_model("boarding_points", "BoardingPoint")
    db_alias = schema_editor.connection.alias

    # Pega todos os objetos do modelo antigo
    old_points = OldBoardingPoint.objects.using(db_alias).all()

    # Cria novos objetos para o novo modelo
    new_points = [
        NewBoardingPoint(
            id=point.id,
            name=point.name,
            address_reference=point.address_reference,
            route_order=point.route_order
        )
        for point in old_points
    ]

    # Usa bulk_create para inserir todos de uma vez (mais eficiente)
    NewBoardingPoint.objects.using(db_alias).bulk_create(new_points)


class Migration(migrations.Migration):

    dependencies = [
        ('boarding_points', '0001_initial'),
        ('common', '0001_initial'), # Substitua pelo nome da ÚLTIMA migração de common
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]