# Generated by Django 5.2.5 on 2025-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_shift",
            field=models.CharField(
                choices=[
                    ("M", "Morning"),
                    ("A", "Afternoon"),
                    ("E", "Evening"),
                    ("M-A", "Morning & Afternoon"),
                    ("A-E", "Afternoon & Evening"),
                ]
            ),
        ),
    ]
