# Generated by Django 5.2.5 on 2025-09-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("students", "0002_alter_student_class_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="boarding_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="common.boardingpoint",
            ),
        ),
    ]
