# Generated by Django 5.2.5 on 2025-09-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boarding_points", "0002_copy_data_from_common"),
        ("students", "0003_student_boarding_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="boarding_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="boarding_points.boardingpoint",
            ),
        ),
    ]
